//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/max/RiderProjects/Leaf/Parsing/Grammar/Leaf.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Leaf.Parsing.Grammar {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LeafParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public interface ILeafVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace([NotNull] LeafParser.NamespaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.operator_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperator_id([NotNull] LeafParser.Operator_idContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] LeafParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.type_member"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_member([NotNull] LeafParser.Type_memberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct([NotNull] LeafParser.StructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] LeafParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.attribute_add"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute_add([NotNull] LeafParser.Attribute_addContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.allocator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAllocator([NotNull] LeafParser.AllocatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.def_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDef_type([NotNull] LeafParser.Def_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.def_func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDef_func([NotNull] LeafParser.Def_funcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.def_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDef_operator([NotNull] LeafParser.Def_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDef([NotNull] LeafParser.DefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.parameter_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_def([NotNull] LeafParser.Parameter_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.function_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_decl([NotNull] LeafParser.Function_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.function_impl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_impl([NotNull] LeafParser.Function_implContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call([NotNull] LeafParser.Function_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.function_scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_scope([NotNull] LeafParser.Function_scopeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteger([NotNull] LeafParser.IntegerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.floating_point"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloating_point([NotNull] LeafParser.Floating_pointContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] LeafParser.ValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.initialization_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitialization_list([NotNull] LeafParser.Initialization_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.conditional_scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditional_scope([NotNull] LeafParser.Conditional_scopeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.var_def_t"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_def_t([NotNull] LeafParser.Var_def_tContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.var_def_v"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_def_v([NotNull] LeafParser.Var_def_vContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.var_ass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_ass([NotNull] LeafParser.Var_assContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.var_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_def([NotNull] LeafParser.Var_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf([NotNull] LeafParser.IfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile([NotNull] LeafParser.WhileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor([NotNull] LeafParser.ForContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn([NotNull] LeafParser.ReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.free"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFree([NotNull] LeafParser.FreeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] LeafParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.generic_def_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_def_list([NotNull] LeafParser.Generic_def_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.generic_impl_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_impl_list([NotNull] LeafParser.Generic_impl_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.ns_import"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNs_import([NotNull] LeafParser.Ns_importContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LeafParser.entry_point"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntry_point([NotNull] LeafParser.Entry_pointContext context);
}
} // namespace Leaf.Parsing.Grammar
